paroj/xpad

xpad.c
Here's the patch for the PDP Afterglow Xbox One controllers. Works after adding these lines with the IDs.
=> Added PDP Afterglow Xbox One controller support

xpad.c
xpad_common_btn -> xpad_btn_common
xpad_btn_pad -> xpad_btn_dpad
xpad_btn -> xpad_btn_original
xpad360_btn -> xpad_btn_360
xpad_abs -> xpad_abs_sticks
xpad_abs_pad -> xpad_abs_dpad
Signed-off-by: Daniel Tobias <dan.g.tob@gmail.com>
NOTE: github diff view seems to default to tabs=8spaces, seems you can fix it by adding '?ts=4' to the end of the url
=> xpad: clarify button arrays

README.md, xpad.c
Should help figure out why the rock candy device isn't working correctly, but is probably useful for much more than that #39 #12
=> xpad: print received packets if DEBUG

xpad.c
This is the xpad.c code from the 4.7 kernel that has better Xbox One pad detection.
According to a Reddit thread at https://redd.it/4w2i4z, I was able to get the Device ID for the new controller that ships with the Xbox One S. User torpet confirms that this works over a wired USB connection, but has not tried wireless with a newer Bluetooth (4.0) dongle.
=> Updated Xbox One Controller detection from 4.7 Linux kernel

xpad.c
Tested on F25 with Steam Home Streaming
Basic functionality enabled, working with local games and with Home streaming games (specifically Elite Dangerous if it matters), Wildcat specific buttons not investigated at this time
=> Added USB IDs for Razer Wildcat

xpad.c
Newer gamepads turn themselves off when the mode button is held down.
For XBOX360W gamepads we must do this this in the driver.
A slight difference here to the original behavior is that the pad will turn off when the button is released instead of during holding, because it simplifies implementation.
=> Input: xpad - Poweroff XBOX360W on mode button long press

xpad.c
Got the Nacon GC100 (newer version of GC100-XF) to work as expected when in xinput mode using this addition
Shows in lsusb as: `Bus 001 Device 002: ID 3285:0607 Nacon GC100`
Like the PR-template says, the `xpad_table` entry seems to be enough so there is none for `xpad_device`
=> Input: xpad - add support for Nacon GC100 controller

xpad.c
Device and vendor ID added and seems to provide support for controller. Tested in Steam and a few games.
=> Add 8BitDo Pro 2 Wired Controller for Xbox support

xpad.c
Added to ensure that triggers are mapped to buttons. Adds devices for Xbox One and Xbox 360/PC modes. This also add missing alternative xbox one vendor id for Hori manufacturer. Closes https://github.com/paroj/xpad/issues/107. 
Gamepad device info from usb-devices:
T:  Bus=02 Lev=02 Prnt=02 Port=05 Cnt=02 Dev#=  4 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=ff Prot=ff MxPS=64 #Cfgs=  1
P:  Vendor=24c6 ProdID=5510 Rev=01.00
S:  Manufacturer=HORI CO.,LTD.
S:  Product=Fighting Commander ONE
S:  SerialNumber=4ADB9EFC
C:  #Ifs= 4 Cfg#= 1 Atr=a0 MxPwr=500mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=5d Prot=01 Driver=xpad
I:  If#=0x1 Alt= 0 #EPs= 4 Cls=ff(vend.) Sub=5d Prot=03 Driver=(none)
I:  If#=0x2 Alt= 0 #EPs= 1 Cls=ff(vend.) Sub=5d Prot=02 Driver=(none)
I:  If#=0x3 Alt= 0 #EPs= 0 …
=> Support Hori Xbox Fighting Commander ONE Gamepad

xpad.c
(Nacon USB vendor == BigBen)
This stick requires: MAP_TRIGGERS_TO_BUTTONS to work properly, this patch takes care of that.
=> Add support for: Nacon - Daija Arcade Stick (PC/X-input mode)

xpad.c
Adds support for the 4 under-controller paddles on the XBOX One Elite Controller. These are mapped to BTN_0/1/2/3, and are ignored when using a standard XBOX One controller. In Steam's controller config, they show up as Buttons 11-14.
=> Input: xpadone - add support for XBOX One Elite paddles

xpad.c
Resolves #31
Second attempt at adding support for XBOX One Elite paddles. This time using BTN_TRIGGER_HAPPY for the paddles instead of BTN. See #194 regarding why the first attempt had to be reverted, see #193 for the original PR.
I've used jstest to verify the bits are working as expected. The button mapping works out as follows:
| Paddle Position | Mapping | Button Number |
| --- | --- | :--- |
| Left hand, upper | BTN_HAPPY3 | 13 |
| Left hand, lower | BTN_HAPPY4 | 14 |
| Right hand, upper | BTN_HAPPY1 | 11 |
| Right hand, lower | BTN_HAPPY2 | 12 |
_Positions correspond to a normal holding position (i.e.: left side = side with DPAD)_
An effort has been made to support every official model and firmware version I could track down info on. The following controllers _should_ have working …
=> Input: xpadone - add support for XBOX One Elite paddles (attempt #2)

xpad.c
[Brook PS3/PS4 to PS Classic/PS2 Super Converter](https://www.brookaccessory.com/detail/44237976/)
[My Blog about this converter (zpp4000)](https://noabody.wordpress.com/2022/04/06/brook-ps3-ps4-to-ps-classic-ps2-super-converter/)
Although 0c12 exists in xpad_device array, this adapter is not recognized as a Generic Xbox 360 gamepad until 0c12 is also added as a vendor in the xpad_table array.  It is the only addition.
As a side note, in Arch-like Manjaro Qonos 21.2.5, xpad (either existing kernel module or one added via dkms) doesn't load on system start or device insertion.  I'm working around this problem with a targetted udev rule that can be done easily by adding the VID/PID of the device:
`echo 'ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0c12", ATTRS{idProduct}=="08f1", …
=> Add Brook zpp4000 PS3/PS4 to PS Classic/PS2 Super Converter

xpad.c
Add support for Wooting analog keyboards (VID 03eb & 31e3)
https://wooting.io/
Signed-off-by: Kyle Gospodnetich [me@kylegospodneti.ch](mailto:me@kylegospodneti.ch)
=> Add support for Wooting analog keyboards

xpad.c
Some third-party Xbox 360 controllers require additional initialization
packets for the controller to start giving input. Some of these controllers
only require one and may break with further, some may require all three. This
change adds a quirks field that allows specifying these initialization
packets, as well as adding the VID/PID for the HORIPAD FPS for Nintendo
Switch, which depends on only the first packet being sent.
Note that it also removes an unused field from the controller type table.
=> Input: xpad - add quriks for 360 controllers

xpad.c
* This allows to turn off the pad without having to release the Xbox (mode) button
Signed-off-by: Davide Garberi <dade.garberi@gmail.com>
=> input: xpad: Switch to workqueue for xpad360w button poweroff

xpad.c
This pull request adds support for the Guitar Hero Live (GHL) Xbox One dongles.
These dongles require a "magic" USB interrupt message to be sent every
8 seconds otherwise the dongle will not report events where the strumbar is hit
while a fret is being held. Therefore, ghl_poke_timer and ghl_urb are added
to struct usb_xpad. ghl_poke_timer ensures periodicity and ghl_urb contains the
"magic" data. The mapping of buttons and axes was chosen to be coherent
with GHL dongles of other consoles (PS3, WiiU & PS4).
Reviewed by @evilynux
Signed-off-by: Daniel Nguyen <daniel.nguyen.1@ens.etsmtl.ca>
=> Support for GHL Xbox One controller

xpad.c
This occurs with MSI GC20 on Ubuntu 22.04.1 LTS.
Signed-off-by: Eldad Zack <eldad@fogrefinery.com>
=> xbox 360: fix null pointer dereference when manufacturer is null

xpad.c
Got this controller today. Plugging it into Windows it shows up as a wired Xbox 360 pad with a vendor ID 0x2dc8 like the other 8BitDo pads, and a device ID of 0x3106. The IDs are the same whether the controller is connected directly with a wire, or via the wireless dongle.
This doesn't include any support for directly seeing the back buttons on the controller, not sure if that's even possible, and I wouldn't even know how to find out.
Edit: I also just verified that this works when the wireless dongle is plugged into the dock as a passthru. IDs and functionality are the same.
Signed-off-by: Josh Cotton <jcotton42@outlook.com>
=> Add support for 8BitDo Ultimate Wireless controller and dongle

xpad.c
8BitDo Pro 2 Wired Controller shares the same USB identifier (2dc8:3106) as a different device, so amend name to reflect that and reduce confusion as the user might think the controller was misdetected.
I have personally tested it and I can confirm that Pro 2 Wired will also not work in XTYPE_XBOXONE mode (buton presses won't register), therefore XTYPE_XBOX360 remains appropriate.
Signed-off-by: Leonardo Brondani Schenkel <leonardo@schenkel.net>
=> Improve name of 8BitDo controller 2dc8:3106

xpad.c
Using the diff from https://www.spinics.net/lists/linux-input/msg75512.html
Of course I don't want to take credit for a diff made by someone else, however it solved my problem that my Turtle Beach Recon controller was not working on Ubuntu 22.04 and other people may find this helpful as well.
It fixes #174
=> Added Turtle Beach Recon support

xpad.c
Support KEY_RECORD for 8BitDo Pro 2...for Xbox
This controller is a "Series S|X": it has the "share" button below the
big Xbox button. However, it reports the status of that button in a
different offset than the official controller.
The button is still recognized by official Microsoft driver in Windows,
so it looks like that both offsets are used in the wild.
Signed-off-by: `Leonardo Brondani Schenkel <leonardo@schenkel.net>`
=> Support KEY_RECORD for 8BitDo Pro 2...for Xbox

xpad.c
Addition of line 379 adds support for the bluetooth/hall effect stick variant of the 8bitdo Ultimate Controller
=> Adding support for 8bitdo Ultimate Bluetooth

xpad.c
Adds support to the ARM controller variant of the Wooting Two HE. Both boards use the same firmware so this new device just works.
=> Input: xpad - add support for wooting two he (arm)

xpad.c
Closes #263 
Tested successfully on openSUSE Tumbleweed
Signed-off-by: Tobias Görgens <tobi.goergens@gmail.com>
=> Add Black Shark Green Ghost controller support

xpad.c
I've added the DeviceID of a very popular Xbox 360 Wireless Receiver, I already made the commit to the Kernel driver upstream.
Although it mimics the Microsoft's VendorID, it is in fact a clone. Taking into account that the original Microsoft Receiver is not being manufactured anymore, this drive can solve dpad issues encontered by those who still use the original 360 Wireless controller but are using a receiver clone.
Signed-off-by: Nilton Perim Neto <niltonperimneto@gmail.com>
=> Added generic X360 Wireless Receiver

xpad.c
Adding support for Surge controllers.
I tested the changes on Ubuntu 24.04 with a Surge Livewire Microwatt controller and everything seems to work with no issues.
https://www.amazon.com/Livewire-Microwatt-Controller-Windows-Gaming-Console/dp/B0CGF9SZZS?ref_=ast_sto_dp&th=1
```console
ubuntu@ubuntu:/usr/src/xpad-0.4$ lsusb -d 2c16:a1b1
Bus 001 Device 056: ID 2c16:a1b1 Priferential Accessories Ltd Surge Wired Controller
```
=> Add support for Surge controllers

xpad.c
Fix #319 
Renamed del_timer_sync to timer_delete_sync.
Reason: https://github.com/torvalds/linux/commit/8fa7292fee5c5240402371ea89ab285ec856c916
Compatibility with older kernels has been preserved.
=> Compatibility with kernel 6.15.0
